# Generated by Django 5.2.5 on 2025-09-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_yogapost_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogapost',
            old_name='images',
            new_name='image2',
        ),
    ]
