# Generated by Django 5.2.5 on 2025-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_images_yogapost_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogapost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yoga_images/'),
        ),
    ]
