# Generated by Django 5.2.5 on 2025-10-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_introduction1_article_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='paragraphs2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
