# Generated by Django 5.2.5 on 2025-10-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_yogapost_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='yoga_images/'),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='introduction3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='paragraphs3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
