# Generated by Django 5.2.5 on 2025-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_yogapost_image3_yogapost_introduction3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='title3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
