# Generated by Django 5.2.5 on 2025-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_yogapost_title3'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='yoga_images/'),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='paragraphs4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
