# Generated by Django 5.2.5 on 2025-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='yoga_images/'),
        ),
    ]
