# Generated by Django 5.2.5 on 2025-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_yogapost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='p1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='p2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='p3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
