# Generated by Django 5.2.5 on 2025-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_yogapost_p1_yogapost_p2_yogapost_p3'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='paragraphs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='titles',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yogapost',
            name='p1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yogapost',
            name='p2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yogapost',
            name='p3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
