# Generated by Django 5.2.5 on 2025-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_alter_yogapost_paragraphs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='catergory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='yogapost',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
