# Generated by Django 5.2.5 on 2025-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_yogapost_catergory_yogapost_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimg', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('shot1', models.CharField(blank=True, max_length=100, null=True)),
                ('shot2', models.CharField(blank=True, max_length=100, null=True)),
                ('title2', models.CharField(max_length=200)),
                ('description3', models.CharField(blank=True, max_length=700, null=True)),
                ('read', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
