# Generated by Django 5.2.5 on 2025-09-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blog_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('paragraph1', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('introduction1', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('created_at1', models.DateTimeField(auto_now_add=True)),
                ('updated_at1', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
