# Generated by Django 5.2.5 on 2025-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_article_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='introduction1',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='article',
            name='paragraph1',
        ),
        migrations.AddField(
            model_name='article',
            name='short1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='short2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description1',
            field=models.TextField(null=True),
        ),
    ]
