# Generated by Django 5.2.5 on 2025-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_yogapost_paragraphs2'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapost',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
